name: Scheduled sync
on:
  schedule:
  - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: 3.6.2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Configuration
      run: |
        git config --local user.name "Github Action"
        git config --local user.email "enchufa2@users.noreply.github.com"
        mkdir $HOME/.config && echo "$TOKEN" > $HOME/.config/copr
        python -m pip install --upgrade pip
        pip install copr-cli
      env:
        TOKEN: ${{ secrets.COPR_TOKEN }}
    - name: Sync with CRAN
      run: |
        Rscript copr-sync.r
        git add specs
        git diff-index --quiet HEAD || git commit -m "sync"
        git push
